// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type User struct {
	UserID      int32
	Name        string
	Email       string
	Password    string
	CreditLimit string
	CurrentDue  string
}
