// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: report.sql

package db

import (
	"context"
)

const getOutstandingBalance = `-- name: GetOutstandingBalance :one
SELECT
    CAST(COALESCE(SUM(current_due), 0.00) AS DECIMAL(10,2)) AS total_due
FROM users
`

func (q *Queries) GetOutstandingBalance(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getOutstandingBalance)
	var total_due string
	err := row.Scan(&total_due)
	return total_due, err
}

const getUserOutstandingDues = `-- name: GetUserOutstandingDues :many
SELECT
    user_id,
    name,
    current_due
FROM users
ORDER BY current_due DESC
`

type GetUserOutstandingDuesRow struct {
	UserID     int32
	Name       string
	CurrentDue string
}

func (q *Queries) GetUserOutstandingDues(ctx context.Context) ([]GetUserOutstandingDuesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserOutstandingDues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserOutstandingDuesRow
	for rows.Next() {
		var i GetUserOutstandingDuesRow
		if err := rows.Scan(&i.UserID, &i.Name, &i.CurrentDue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersAtCreditLimit = `-- name: GetUsersAtCreditLimit :many
SELECT
    user_id,
    name,
    credit_limit,
    current_due
FROM users
WHERE current_due >= credit_limit
`

type GetUsersAtCreditLimitRow struct {
	UserID      int32
	Name        string
	CreditLimit string
	CurrentDue  string
}

func (q *Queries) GetUsersAtCreditLimit(ctx context.Context) ([]GetUsersAtCreditLimitRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsersAtCreditLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersAtCreditLimitRow
	for rows.Next() {
		var i GetUsersAtCreditLimitRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.CreditLimit,
			&i.CurrentDue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
