// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"
	"database/sql"
)

const checkEmailExists = `-- name: CheckEmailExists :one
SELECT EXISTS(
    SELECT 1
    FROM users
    WHERE email = ?
)
`

func (q *Queries) CheckEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (
    name,
    email,
    password
)
VALUES (
    ?,
    ?,
    ?
)
`

type CreateUserParams struct {
	Name     string
	Email    string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser, arg.Name, arg.Email, arg.Password)
}

const decreaseUserDue = `-- name: DecreaseUserDue :execresult
UPDATE users
SET current_due = ?
WHERE user_id = ?
`

type DecreaseUserDueParams struct {
	CurrentDue string
	UserID     int32
}

func (q *Queries) DecreaseUserDue(ctx context.Context, arg DecreaseUserDueParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, decreaseUserDue, arg.CurrentDue, arg.UserID)
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    user_id,
    name,
    email,
    password,
    credit_limit,
    current_due
FROM users
WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreditLimit,
		&i.CurrentDue,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    user_id,
    name,
    email,
    credit_limit,
    current_due
FROM users
WHERE user_id = ?
`

type GetUserByIDRow struct {
	UserID      int32
	Name        string
	Email       string
	CreditLimit string
	CurrentDue  string
}

func (q *Queries) GetUserByID(ctx context.Context, userID int32) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, userID)
	var i GetUserByIDRow
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.CreditLimit,
		&i.CurrentDue,
	)
	return i, err
}

const getUserByIDForUpdate = `-- name: GetUserByIDForUpdate :one
SELECT
    user_id,
    name,
    email,
    credit_limit,
    current_due
FROM users
WHERE user_id = ?
FOR UPDATE
`

type GetUserByIDForUpdateRow struct {
	UserID      int32
	Name        string
	Email       string
	CreditLimit string
	CurrentDue  string
}

func (q *Queries) GetUserByIDForUpdate(ctx context.Context, userID int32) (GetUserByIDForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByIDForUpdate, userID)
	var i GetUserByIDForUpdateRow
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.CreditLimit,
		&i.CurrentDue,
	)
	return i, err
}

const increaseUserDue = `-- name: IncreaseUserDue :execresult
UPDATE users
SET current_due = ?
WHERE user_id = ?
`

type IncreaseUserDueParams struct {
	CurrentDue string
	UserID     int32
}

func (q *Queries) IncreaseUserDue(ctx context.Context, arg IncreaseUserDueParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, increaseUserDue, arg.CurrentDue, arg.UserID)
}

const listUsers = `-- name: ListUsers :many
SELECT
    user_id,
    name,
    email,
    credit_limit,
    current_due
FROM users
ORDER BY user_id
`

type ListUsersRow struct {
	UserID      int32
	Name        string
	Email       string
	CreditLimit string
	CurrentDue  string
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.Email,
			&i.CreditLimit,
			&i.CurrentDue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
