// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Payment struct {
	PaymentID int32
	UserID    int32
	Amount    string
	PaidAt    sql.NullTime
}

type Transaction struct {
	TransactionID        int32
	UserID               int32
	MerchantID           int32
	Amount               string
	CommissionPercentage string
	CommissionAmount     string
	CreatedAt            sql.NullTime
}
