// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package db

import (
	"context"
	"database/sql"
)

const createPayment = `-- name: CreatePayment :execresult
INSERT INTO payments (
    user_id,
    amount
)
VALUES (?, ?)
`

type CreatePaymentParams struct {
	UserID int32
	Amount string
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPayment, arg.UserID, arg.Amount)
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT
    payment_id,
    user_id,
    amount,
    paid_at
FROM payments
WHERE payment_id = ?
`

func (q *Queries) GetPaymentByID(ctx context.Context, paymentID int32) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByID, paymentID)
	var i Payment
	err := row.Scan(
		&i.PaymentID,
		&i.UserID,
		&i.Amount,
		&i.PaidAt,
	)
	return i, err
}

const listUserPayments = `-- name: ListUserPayments :many
SELECT
    payment_id,
    user_id,
    amount,
    paid_at
FROM payments
WHERE user_id = ?
ORDER BY paid_at DESC
`

func (q *Queries) ListUserPayments(ctx context.Context, userID int32) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, listUserPayments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.PaymentID,
			&i.UserID,
			&i.Amount,
			&i.PaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
