// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: report.sql

package db

import (
	"context"
)

const getMerchantCommissionSummary = `-- name: GetMerchantCommissionSummary :many
SELECT
    merchant_id,
    CAST(
        COALESCE(SUM(commission_amount), 0.00)
        AS DECIMAL(10,2)
    ) AS total_commission
FROM transactions
GROUP BY merchant_id
ORDER BY total_commission DESC
`

type GetMerchantCommissionSummaryRow struct {
	MerchantID      int32
	TotalCommission string
}

func (q *Queries) GetMerchantCommissionSummary(ctx context.Context) ([]GetMerchantCommissionSummaryRow, error) {
	rows, err := q.db.QueryContext(ctx, getMerchantCommissionSummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMerchantCommissionSummaryRow
	for rows.Next() {
		var i GetMerchantCommissionSummaryRow
		if err := rows.Scan(&i.MerchantID, &i.TotalCommission); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
