// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction.sql

package db

import (
	"context"
	"database/sql"
)

const createTransaction = `-- name: CreateTransaction :execresult
INSERT INTO transactions (
    user_id,
    merchant_id,
    amount,
    commission_percentage,
    commission_amount
)
VALUES (
    ?,
    ?,
    ?,
    ?,
    ?
)
`

type CreateTransactionParams struct {
	UserID               int32
	MerchantID           int32
	Amount               string
	CommissionPercentage string
	CommissionAmount     string
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTransaction,
		arg.UserID,
		arg.MerchantID,
		arg.Amount,
		arg.CommissionPercentage,
		arg.CommissionAmount,
	)
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT
    transaction_id,
    user_id,
    merchant_id,
    amount,
    commission_percentage,
    commission_amount,
    created_at
FROM transactions
WHERE transaction_id = ?
`

func (q *Queries) GetTransactionByID(ctx context.Context, transactionID int32) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByID, transactionID)
	var i Transaction
	err := row.Scan(
		&i.TransactionID,
		&i.UserID,
		&i.MerchantID,
		&i.Amount,
		&i.CommissionPercentage,
		&i.CommissionAmount,
		&i.CreatedAt,
	)
	return i, err
}

const listMerchantTransactions = `-- name: ListMerchantTransactions :many
SELECT
    transaction_id,
    user_id,
    merchant_id,
    amount,
    commission_percentage,
    commission_amount,
    created_at
FROM transactions
WHERE merchant_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListMerchantTransactions(ctx context.Context, merchantID int32) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listMerchantTransactions, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.TransactionID,
			&i.UserID,
			&i.MerchantID,
			&i.Amount,
			&i.CommissionPercentage,
			&i.CommissionAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT
    transaction_id,
    user_id,
    merchant_id,
    amount,
    commission_percentage,
    commission_amount,
    created_at
FROM transactions
ORDER BY transaction_id DESC
`

func (q *Queries) ListTransactions(ctx context.Context) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.TransactionID,
			&i.UserID,
			&i.MerchantID,
			&i.Amount,
			&i.CommissionPercentage,
			&i.CommissionAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTransactions = `-- name: ListUserTransactions :many
SELECT
    transaction_id,
    user_id,
    merchant_id,
    amount,
    commission_percentage,
    commission_amount,
    created_at
FROM transactions
WHERE user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListUserTransactions(ctx context.Context, userID int32) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listUserTransactions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.TransactionID,
			&i.UserID,
			&i.MerchantID,
			&i.Amount,
			&i.CommissionPercentage,
			&i.CommissionAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
