// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merchant.sql

package db

import (
	"context"
	"database/sql"
)

const checkMerchantEmailExists = `-- name: CheckMerchantEmailExists :one
SELECT EXISTS(
    SELECT 1
    FROM merchants
    WHERE email = ?
)
`

func (q *Queries) CheckMerchantEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkMerchantEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createMerchant = `-- name: CreateMerchant :execresult
INSERT INTO merchants (
    name,
    email,
    phone,
    password_hash,
    commission_percentage
)
VALUES (?, ?, ?, ?, ?)
`

type CreateMerchantParams struct {
	Name                 string
	Email                string
	Phone                string
	PasswordHash         string
	CommissionPercentage string
}

func (q *Queries) CreateMerchant(ctx context.Context, arg CreateMerchantParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMerchant,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.CommissionPercentage,
	)
}

const getMerchantByEmail = `-- name: GetMerchantByEmail :one
SELECT
    merchant_id,
    name,
    email,
    phone,
    password_hash,
    commission_percentage
FROM merchants
WHERE email = ?
`

func (q *Queries) GetMerchantByEmail(ctx context.Context, email string) (Merchant, error) {
	row := q.db.QueryRowContext(ctx, getMerchantByEmail, email)
	var i Merchant
	err := row.Scan(
		&i.MerchantID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.CommissionPercentage,
	)
	return i, err
}

const getMerchantByID = `-- name: GetMerchantByID :one
SELECT
    merchant_id,
    name,
    phone,
    email,
    commission_percentage
FROM merchants
WHERE merchant_id = ?
`

type GetMerchantByIDRow struct {
	MerchantID           int32
	Name                 string
	Phone                string
	Email                string
	CommissionPercentage string
}

func (q *Queries) GetMerchantByID(ctx context.Context, merchantID int32) (GetMerchantByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMerchantByID, merchantID)
	var i GetMerchantByIDRow
	err := row.Scan(
		&i.MerchantID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.CommissionPercentage,
	)
	return i, err
}

const listMerchants = `-- name: ListMerchants :many
SELECT
    merchant_id,
    name,
    phone,
    email,
    commission_percentage
FROM merchants
ORDER BY merchant_id
`

type ListMerchantsRow struct {
	MerchantID           int32
	Name                 string
	Phone                string
	Email                string
	CommissionPercentage string
}

func (q *Queries) ListMerchants(ctx context.Context) ([]ListMerchantsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMerchants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMerchantsRow
	for rows.Next() {
		var i ListMerchantsRow
		if err := rows.Scan(
			&i.MerchantID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.CommissionPercentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMerchantCommission = `-- name: UpdateMerchantCommission :execresult
UPDATE merchants
SET commission_percentage = ?
WHERE merchant_id = ?
`

type UpdateMerchantCommissionParams struct {
	CommissionPercentage string
	MerchantID           int32
}

func (q *Queries) UpdateMerchantCommission(ctx context.Context, arg UpdateMerchantCommissionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateMerchantCommission, arg.CommissionPercentage, arg.MerchantID)
}
