// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Merchant struct {
	MerchantID           int32
	Name                 string
	Email                string
	Phone                string
	PasswordHash         string
	CommissionPercentage string
}
